name: carbon-intensity-sdk

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Integration Tests
      run: dotnet test --no-build --verbosity normal
