name: carbon-intensity-sdk

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Integration Tests
      run: dotnet test --no-build --verbosity normal

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v4
    - name: debug
      run: ls -l

    - name: debug
      run: pwd

    - name: Create package
      run: dotnet pack --output nupkgs

    - name: Publish package
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json